package com.pixelfactory.event.domain;

public enum FactoryEventType {
    WORK_ORDER_CREATED,
    WORK_ORDER_ASSIGNED,
    WORK_ORDER_STARTED,
    WORK_ORDER_ON_HOLD,
    MATERIAL_MOVE_REQUESTED,
    AGV_MOVE_STARTED,
    AGV_ARRIVED,
    EQUIPMENT_STATUS_CHANGED,
    PRODUCTION_STARTED,
    PRODUCTION_COMPLETED,
    INSPECTION_STARTED,
    INSPECTION_PASSED,
    INSPECTION_FAILED,
    AI_ANOMALY_DETECTED,
    MRB_CREATED,
    PIGEON_TO_QMS,
    QMS_ACTION_STARTED,
    QMS_ACTION_COMPLETED,
    PIGEON_TO_OPERATOR,
    FINISHED_GOODS_MOVE_STARTED,
    WORK_ORDER_COMPLETED
}
