package com.pixelfactory.event.domain;

public enum FactoryEventType {
    WORK_ORDER_CREATED,
    WORK_ORDER_ASSIGNED,
    WORK_ORDER_STARTED,
    WORK_ORDER_ON_HOLD,
    EQUIPMENT_STATUS_CHANGED,
    CYCLE_COMPLETED,
    PRODUCTION_STARTED,
    PRODUCTION_COMPLETED,
    INSPECTION_STARTED,
    INSPECTION_PASSED,
    INSPECTION_FAILED,
    AI_ANOMALY_DETECTED,
    NOTIFICATION_SENT,
    WORK_ORDER_COMPLETED
}
